[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/es/*"
to = "/es/404.html"
status = 404

[[redirects]]
from = "/ro/*"
to = "/ro/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/404.html"
status = 404

[[redirects]]
from = "/en/*"
to = "/en/contact-success"
status = 302
